DSL skill
eora-dialog-systems/DeepPavlov pull request #2
Opened 2019-07-01 13:56 UTC by Nitrogen13

2019-07-04 07:29 UTC, strawberrypie requested changes

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +from .handlers.handler import Handler
Выше RegexHandler импортируется через абсолютный путь, думаю что нужно тут так же, либо объединить:
```python
from deeppavlov.skills.dsl_skill.handlers import Handler, RegexHandler
```

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +class DSLMeta(ABCMeta):
Нужен docstring, т.к. это основной класс для реализации данной механики.

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +        cls.universal_state = []
```python
# Handlers that can be activated from any state
cls.universal_handlers = []
```

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +        cls.handlers = {}
Попробуем тут сменить названия на более подходящие, раз есть такая возможность.
```python
cls.state_to_handler = defaultdict(list)
```

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +            if handler.state not in cls.handlers:
Здесь внести поправки насчет правки выше (`state_to_handler`).

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +    def __initialize_class(cls, on_invalid_command: str = "Простите, я вас не понял", *args, **kwargs):
Давай переименуем в `__init__class`, чтобы чуть более было явно что этот метод прикрепляется к классу как `__init__`

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +    def __handle_batch(cls: 'DSLMeta', utterances_batch: List, history_batch: List = [], states_batch: List = []) \
Давай вместо такого переноса отформатируем так:
```python
def __handle_batch(cls: 'DSLMeta',
                   utterances_batch: List,
                   history_batch: List = [],
                   states_batch: List = []) -> Tuple[List, ...]:
```
Нагляднее и чуть проще править.

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +        for utterance, history, state in zip_longest(utterances_batch, history_batch, states_batch):
Давай заюзаем `unzip` (если @sVerentsov не против).

https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.unzip

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +        if state:
Может в одну строчку?
```python
available_handlers = cls.handlers.get(state) if state else []
```

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +        Selects handler that will process request
Selects handler with the highest priority that could be triggered from the passed state and message.

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +        :return: response dict
Дока врет, возвращается `ResponseType `.

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/utils.py
> +ResponseType = Tuple[str, float, Optional[str]]
Лучше сделать так:
```python
class ResponseType(NamedTuple):
    response: str
    confidence: float
    state: Optional[str]
```
Работает аналогично, но понятно какой тип за что отвечает.

2019-07-04 07:29 UTC, strawberrypie commented on tests/test_dsl_skill.py
> +                                  ]
чет улетела

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +            return response, 1, new_state
Вообще говоря, кажется Handler уже должен ResponseType возвращать, а тут происходит распаковка и потом дальнейшая запаковка. Может сразу возвращать ответ хэндлера?
```python
try:
    return handler(message, history, state)
except Exception as exc:
    return str(exc), 1.0, None
```

2019-07-04 07:29 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +        message = re.sub(r'[\"\']', '', utterance.lower())
Думаю что нужно убрать и использовать при необходимости встроенные в deeppavlov возможности препроцессинга (т.е. перед скиллом в пайпе будет препроцессор).

2019-07-04 09:29 UTC, Nitrogen13 commented on tests/test_dsl_skill.py
> +                                  ]
Форматнул блэком

2019-07-04 12:10 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +        for utterance, history, state in zip_longest(utterances_batch, history_batch, states_batch):
```python
return unzip(map(cls.handle, zip_longest(utterances_batch, history_batch, states_batch)))
```

2019-07-04 12:30 UTC, Nitrogen13 commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +        for utterance, history, state in zip_longest(utterances_batch, history_batch, states_batch):
starmap

2019-07-11 16:35 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +from more_itertools import unzip
Либа нигде не указана в requirements

2019-07-11 16:35 UTC, strawberrypie commented on docs/skills/dsl_skill.rst
> +    skill_config["chainer"]["pipe"][1]["class_name"] = "SimpleSkill"
Почему не указать это в конфиге?

2019-07-11 16:35 UTC, strawberrypie commented on docs/skills/dsl_skill.rst
> +    skill_config["chainer"]["pipe"][1]["class_name"] = "SimpleSkill"
Кажется через register будет работать.

2019-07-11 16:35 UTC, strawberrypie commented on deeppavlov/skills/dsl_skill/dsl_skill.py
> +    This metaclass is used for create a skill.
Нужно написать что полученный навык регистрируется по своему названию в общеем реестре.

2019-07-15 12:24 UTC, merged